# Generated by Django 2.2.28 on 2023-11-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(max_length=30),
        ),
    ]
